site_name: Learn_
site_url: https://kimgunkrok123.github.io/learn_/
repo_name: Learn_
repo_url: https://github.com/kimgunkrok123/learn_

theme: 
  name: material
  language: en
  icon:
    edit: material/pencil 
    view: material/eye
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference
      accent: blue
      primary: black
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.footer
    - content.action.edit
    - content.action.view

plugins:
  - search
  - tags
  - privacy
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: squidfunk/mkdocs-material
      branch: main

nav:
  - Home: index.md
  - Backend: Backend/index.md
  - Black: Black/index.md
  - DB: DB/index.md
  - Frontend: Frontend/index.md
  - Game: Game/index.md
  - Language: Language/index.md
  - Linux: Linux/index.md
  - Start: Start/index.md

extra:
  homepage: https://kimgunkrok123.github.io/learn_/
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/kimg92748/
    - icon: fontawesome/brands/github
      link: https://github.com/kimgunkrok123/learn_
  consent:
    title: "cookie consent"
    description: "This site uses cookies to ensure you get the best experience on our website."
  analytics:
    provider: google
    tracking_id: "G-YN85DPDQQP"
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - pymdownx.superfences
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - abbr