site_name: learn_
repo_url: https://github.com/kimgunkrok123/learn_
repo_name: kimgunkrok123/learn_

theme:
  name: material
  language: ko
  features:
  - navigation.footer
  icon:
  repo: fontawesome/brands/git-alt
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      scheme: slate
      primary: black
      accent: blue

extra: 
  consent:
    title: Cookie consent
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/kimg92748/
    - icon: fontawesome/brands/github
      link: https://github.com/kimgunkrok123/learn_

plugins: 
  - search
  - git-authors
  #- macros
  #- pdf-export
  - table-reader
  - awesome-pages
  - section-index
  - git-committers:
      token: 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
      repository: kimgunkrok123/learn_
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true 
      minify_js: true   
      minify_css: true    